language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

jobs:
  include:
    - stage: doc
      script:
        - make install-docs-requirements
        - make docs

install:
  - pip3 install -U setuptools
  - pip3 install sphinx
  - pip3 install cffi
  - python setup.py develop
  - make install-tests-requirements

script:
  - make test
  - #make test-docs

after_success:
  - bash <(curl -s https://codecov.io/bash)
